# k8s/base/frontend-service/pdb.yaml
# Memastikan ketersediaan minimum frontend selama gangguan yang direncanakan.

apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: frontend-service-pdb
  namespace: frontend-service
  labels:
    app.kubernetes.io/name: frontend-microservice
    app.kubernetes.io/component: pdb
spec:
  minAvailable: 1 # Minimal 1 pod harus tetap menyala saat ada gangguan/maintenance
  selector:
    matchLabels:
      app: frontend-service
