# k8s/base/dashboard-service/pdb.yaml
# Memastikan ketersediaan minimum dashboard selama gangguan yang direncanakan.

apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: dashboard-service-pdb
  namespace: dashboard-service
  labels:
    app.kubernetes.io/name: dashboard-microservice
    app.kubernetes.io/component: pdb
spec:
  minAvailable: 1 # Minimal 1 pod harus tetap aktif saat maintenance node
  selector:
    matchLabels:
      app: dashboard-service
