# k8s/base/frontend-service/registry-secret.yaml
# Docker registry credentials for pulling images for frontend-service.

apiVersion: v1
kind: Secret
metadata:
  name: registry-credentials
  namespace: frontend-service
  labels:
    app.kubernetes.io/name: frontend-microservice
    app.kubernetes.io/component: registry-secret
type: kubernetes.io/dockerconfigjson
data:
  # Gunakan base64 dari .dockerconfigjson Anda di sini
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS55b3VyZG9tYWluLmNvbSI6eyJhdXRoIjoiWVhCd2JHbGpZWFJwYjI0NlVHRnpjM2R2Y21RPSJ9fX0=
