# k8s/base/dashboard-service/registry-secret.yaml
# Docker registry credentials for pulling images for dashboard-service.

apiVersion: v1
kind: Secret
metadata:
  name: registry-credentials
  namespace: dashboard-service
  labels:
    app.kubernetes.io/name: dashboard-microservice
    app.kubernetes.io/component: registry-secret
type: kubernetes.io/dockerconfigjson
data:
  # Gunakan base64 dari .dockerconfigjson Anda di sini
  # Hati-hati: Pastikan data ini dienkripsi atau dikelola via Sealed Secrets di Production
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS55b3VyZG9tYWluLmNvbSI6eyJhdXRoIjoiWVhCd2JHbGpZWFJwYjI0NlVHRnpjM2R2Y21RPSJ9fX0=
