# ServiceAccount for Frontend

apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-sa
  namespace: frontend
  labels:
    app.kubernetes.io/name:      frontend
    app.kubernetes.io/component: serviceaccount
automountServiceAccountToken: false
