# k8s/base/dashboard-service/sa.yaml
# Dedicated ServiceAccount for dashboard-microservice.

apiVersion: v1
kind: ServiceAccount
metadata:
  name: dashboard-service-sa
  namespace: dashboard-service
  labels:
    app.kubernetes.io/name: dashboard-microservice
    app.kubernetes.io/component: serviceaccount
# Keamanan: Jangan pasang token API secara otomatis jika tidak dibutuhkan
automountServiceAccountToken: false
