apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secret
  namespace: auth-service
  labels:
    app.kubernetes.io/name:      auth-microservice
    app.kubernetes.io/component: secret
type: Opaque
data:
  # echo -n "postgresql://postgres:yourpassword@postgres-svc.postgres.svc.cluster.local:5432/auth_db" | base64
  DATABASE_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzOkpvNHA0SDZ6UjAwd0BhdXRoLXBvc3RncmVzLmF1dGgtcG9zdGdyZXMuc3ZjLmNsdXN0ZXIubG9jYWw6NTQzMi9hdXRoX2Ri
  # echo -n "$(openssl rand -hex 64)" | base64
  JWT_SECRET: ZDhkYzgwMmYzOTU1ZWFlN2M4OGJiZDdjOTNjMDcxZDE5NTUxMDVkNjMzMDEzMTE4ODc5YWM3OGVjZmVmNGMxOTUyMzJmYTRmYzg3NTllMjY1MmVjNDU2OWFlMmJiZmM2N2E2NGJiOGExN2E1ZWZlM2QwNTJkNjcwNmNkNmU1MTM=
  # echo -n "admin" | base64
  ADMIN_USERNAME: YWRtaW4=
  # echo -n "YourStrongAdminPassword!" | base64
  ADMIN_PASSWORD: QWRtaW5AMTIzNCE=