# Service for Frontend

apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: frontend
  labels:
    app.kubernetes.io/name:      frontend
    app.kubernetes.io/component: server
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
    - name:       http
      port:       80
      targetPort: http
      protocol:   TCP

---

# NodePort Service (opsional, digunakan untuk akses langsung tanpa Ingress)
# Uncomment jika diperlukan:

apiVersion: v1
kind: Service
metadata:
  name: frontend-np
  namespace: frontend
  labels:
    app.kubernetes.io/name:      frontend
    app.kubernetes.io/component: server-nodeport
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - name:       http
      port:       80
      targetPort: http
      protocol:   TCP
      nodePort:   30080
